version: '3.8'
services:
  postgres:
    image: 'bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=tasks
      - POSTGRESQL_PORT_NUMBER=5432
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/bitnami/postgresql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge