@baseUrl = http://localhost:3001

GET {{baseUrl}}/tasks HTTP/1.1

###

POST  {{baseUrl}}/task HTTP/1.1
Content-Type: application/json

{
  "name": "Estudar Javascript",
  "text": "Preciso estudar javascript na Rocketseat",
  "createdBy": "a0568836-8a9e-4b2b-8ada-b4b35527019b",
  "startDate": "8/4/2023, 2:00 am",
  "endDate": "8/4/2024, 12:00 am"
}

###

GET {{baseUrl}}/tasks/a0568836-8a9e-4b2b-8ada-b4b35527019b

###

DELETE {{baseUrl}}/task/dd2c7eab-ed9e-4246-b846-476741953c65

###

PUT {{baseUrl}}/task/change-status/701b0930-9b7e-42be-ae59-9fb14ab7327a